stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  environment: shell
  tags:
    - windows_web_mobile
  script:
    - echo "Compiling the code..."
    - cmd /c build-webmobile.bat
    - echo "Compile complete."
  artifacts:
    expire_in: 20min
    paths:
      - ./build/web-mobile/

# Deploy in Server
deploy-job:
  stage: deploy
  environment: shell
  tags:
    - deployPage
  script:
    - cd ../../../../../../
    - ./deploy.sh

# Flush CDN
flushcache:
  stage: flushcache
  image: python:alpine
  script:
    - cd python-flushcache
    - python -m pip install -r requirements.txt
    - python main.py
